services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: hoctap_backend
    restart: unless-stopped
    env_file: ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hoctap_frontend
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: hoctap_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: hoctap_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://nginx:80
    depends_on:
      - nginx
